allowed-origins: http://localhost:4200

spring:
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    async:
      request-timeout: 300000

rhizomer:
  default-password: password
  sparql-timeout: 300000
  omit:
    properties: wikiPage
    classes: http://www.w3.org/2002/07/owl, http://www.w3.org/1999/02/22-rdf-syntax-ns, http://www.w3.org/2000/01/rdf-schema
groq:
  api:
    key: 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
logging:
  file:
    name: myapp.log